config/routes.rb
SecretShareAjax::Application.routes.draw do
  resources :users, :only => [:index, :create, :new, :show] do
    resources :secrets, :only => [:new]
    resources :friendships, :only => [:create, :destroy]
  end
  resource :session, :only => [:create, :destroy, :new]
  resources :secrets, :only => [:create]

  root :to => "users#show"
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  validates :in_friend_id, :out_friend_id, presence: true

  belongs_to :out_friend,
             :foreign_key => :out_friend_id,
             :class_name => "User"

  belongs_to :in_friend,
             :foreign_key => :in_friend_id,
             :class_name => "User"

   def self.can_friend?(out_friend_id, in_friend_id)
     (in_friend_id != out_friend_id) &&
        !Friendship.exists?(out_friend_id: out_friend_id,
                           in_friend_id: in_friend_id)
   end

   def self.can_unfriend?(out_friend_id, in_friend_id)
     !self.can_friend?(out_friend_id, in_friend_id) &&
       (out_friend_id != in_friend_id)
   end

end

app/models/secret.rb
class Secret < ActiveRecord::Base
  validates :author_id, :recipient_id, :title, :presence => true

  belongs_to :recipient, :class_name => "User"
  belongs_to :author, :class_name => "User"

  has_many :secret_taggings
  has_many :tags, through: :secret_taggings

end

app/models/secret_tagging.rb
class SecretTagging < ActiveRecord::Base
  validates :tag_id, presence: true
  belongs_to :secret
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates :name, presence: true

  has_many :secret_taggings
  has_many :users, through: :secret_taggings
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  has_many(
    :authored_secrets,
    :class_name => "Secret",
    :foreign_key => :author_id
  )

  has_many(
    :received_secrets,
    :class_name => "Secret",
    :foreign_key => :recipient_id
  )

  has_many(
    :friendships,
    :class_name => "Friendship",
    :foreign_key => :in_friend_id
  )

  has_many(
    :friends,
    :through => :friendships,
    :source => :out_friend
  )

  validates :password_digest, :presence => { :message => "Password can't be blank" }
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :session_token, :presence => true
  validates :username, :presence => true

  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)

    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user, :signed_in?

  def current_user
    return nil unless session[:session_token]
    User.find_by_session_token(session[:session_token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def logout_current_user!
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
  end

  def require_current_user!
    redirect_to new_session_url unless signed_in?
  end

  def require_no_current_user!
    redirect_to user_url(current_user) if signed_in?
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    @friendship = Friendship.new
    @friendship.in_friend_id = current_user.id
    @friendship.out_friend_id = params[:user_id]

    if @friendship.save!
      render :json => @friendship.to_json
    else
      render :json => @friendship.errors
    end
  end

  def destroy
    @friendship = Friendship.find_by(in_friend_id: current_user.id,                                                   out_friend_id: params[:user_id])
    if @friendship
      @friendship.destroy
      render :json => "Friendship destroyed".to_json
    else
      render :json => @friendship.errors
    end
  end

end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController
  def new
    @secret = Secret.new
    @recipient = User.find(params[:user_id])
  end

  def create
    @secret = Secret.new(secret_params)
    @secret.author_id = current_user.id
    # @secret.tags.build(tag_params)
    # fail
    if @secret.save
      render :json => @secret
    else
      render :json => @secret.errors.full_messages, :status => 422
    end
    # redirect_to user_url(User.find(params[:secret][:recipient_id]))
  end

  private

  def secret_params
    params.require(:secret).permit(:title, :recipient_id, :tag_ids =>[])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :require_no_current_user!, :only => [:create, :new]
  before_filter :require_current_user!, :only => [:destroy]

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user.nil?
      render :json => "Credentials were wrong"
    else
      self.sign_in(user)
      redirect_to user_url(user)
    end
  end

  def destroy
    logout_current_user!
    redirect_to new_session_url
  end

  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_current_user!, :only => [:index, :show]
  before_filter :require_no_current_user!, :only => [:create, :new]

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(@user)
      redirect_to user_url(@user)
    else
      render :json => @user.errors.full_messages
    end
  end

  def new
    @user = User.new
  end

  def show
    if !params.include?(:id)
      redirect_to user_url(current_user)
      return
    end

    @user = User.find(params[:id])
    @secret = Secret.new
    @tags = Tag.all
  end

  def index
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/secrets_helper.rb
module SecretsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SecretShareAjax</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if signed_in? %>
  <ul>
    <li>Logged in as: <%= current_user.username %></li>
    <li><%= button_to "Logout", session_url, :method => :delete %></li>
  </ul>
<% end %>

<%= yield %>

</body>
</html>

app/views/secrets/_form.html.erb
<form id="new-secret" action="<%= secrets_url %>" method="post">
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label for="title">Title</label>
  <input type="text"
         name="secret[title]"
         value="<%= secret.title %>"
         id="title">

  <input type="hidden" name="secret[recipient_id]" value="<%= recipient.id %>">

  <label for="tags">

  <select name="secret[tag_ids][]" id="tags">
    <% tags.each do |tag| %>
      <option value="<%= tag.id %>"><%= tag.name %></option>
    <% end %>
  </select>

  <div class="secret-tag-selects"></div>

  <p><input type="submit" value="Continue &rarr;"></p>
</form>

app/views/secrets/new.html.erb
<%= render "form", secret: @secret, recipient: @recipient %>

app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? "put" : "post") %>
<% message = (user.persisted? ? "Update user" : "Create user") %>

<form action="<%= action %>" method="post">
  <input
     name="_method"
     type="hidden"
     value="<%= method %>">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <label for="user_username">Username</label>
  <input
     id="user_username"
     name="user[username]"
     type="text">
  <br>

  <label for="user_password">Password</label>
  <input
     id="user_password"
     name="user[password]"
     type="password">
  <br>

  <input type="submit" value="<%= message %>">
</form>

app/views/users/index.html.erb
<% @current_id = -1 unless @current_id = current_user %>
<!-- cut down on n+1 queries -->

<h1>All the people</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.username, user_url(user) %>
      <% if Friendship.can_friend?(user.id, @current_id) %>
        <div class="friend-buttons can-friend" data-test="1">
      <% elsif Friendship.can_unfriend?(user.id, @current_id) %>
        <div class="friend-buttons can-unfriend">
      <% else %>
        <div class="friend-buttons self">
      <% end %>
        <button class="friend"
                data-userid="<%= user.id %>">
          New Friend
        </button>
      <% friendship = Friendship.find_by(in_friend_id: @current_id,
                                         out_friend_id: user.id) %>
      <% friendship = friendship ? friendship.id : -1 %>
        <button class="unfriend"
                data-userid="<%= user.id %>"
                data-friendshipid="<%= friendship %>">
          Unfriend
        </button>
      </div>
    </li>
  <% end %>
</ul>

<script>
  $(function() {

    $('button').on("click", function(event) {
      var $friendButton = $(event.target);
      if ($friendButton.attr('class') === 'friend') {
          var userurl = "/users/" +
                         $friendButton.data("userid") +
                         "/friendships";
          var action = 'POST';
      } else {
        var userurl = "/users/" + $friendButton.data("userid") +
                       "/friendships/" + $friendButton.data("friendshipid");
        var action = 'DELETE';
      }

      $.ajax({
        url: userurl,
        type: action,
        success: function() {
          $friendButton.parent().toggleClass("can-friend can-unfriend");
          // $friendButton.remove();
        },
        error: function () {
          alert(arguments);
        }
      })
    });
  });
</script>

app/views/users/new.html.erb
<h1>Create User</h1>

<%= render "form", :user => @user %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<h2>Post a Secret</h2>


<div id="form-container"></div>

<a href="#" class="add-secret-tag">Add Another Tag</a>

<script type="text/template" id="form-template">
  <%= render "secrets/form", secret: @secret, recipient: @user, tags: @tags %>
</script>

<h2>Secrets</h2>
<ul id='secrets-list'>
  <% @user.received_secrets.each do |secret| %>
    <li>
      <%= secret.title %> |
      <% secret.tags.each do |tag| %>
        <%= tag.name %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= link_to "Back to all users", users_url %>

<script id="supah_tags" type="application/json">
  { "tags": <%= @tags.to_json.html_safe %> }
</script>

<script type="template/underscore" id="tag-options">
  <select name="secret[tag_ids][]">
    <option></option>
    <%% _(tags).each(function (tag) { %>
      <option value="<%%= tag.id %>"><%%= tag.name %></option>
    <%% }); %>
  </select>
</script>

<script>

  $(function() {
    $('.add-secret-tag').on('click', function(event) {
      event.preventDefault();
      debugger
      var data = JSON.parse($("#supah_tags").html());

      var template = $("#tag-options").html();
      var templateFn = _.template(template);
      var renderedContent = templateFn(data);
      $(".secret-tag-selects").append(renderedContent);
    });

    var template = _.template($('#form-template').html());
    $('#form-container').html(template);

    var addSecret = function(secret) {
      $('ul#secrets-list:first').prepend('<li>' + secret.title + '</li>');
    };

    var submitHandler = function() {
      $('#new-secret').on('submit', function(event) {
        event.preventDefault(); // prevent browser from handling the request
        var $form = $(this);
        var data = $form.serialize();
        $.ajax({
          url: $form.attr('action'),
          type: 'POST',
          data: data,
          success: function (secret) {
            addSecret(secret);
            $('#title').val("");
          },
          error: function() {
            alert(arguments);
          }
        })
      })
    };
    submitHandler();
  });
</script>